global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flyencoder-controlplane'
    static_configs:
      - targets: ['controlplane:8080']
    metrics_path: '/metrics'

  - job_name: 'flyencoder-worker'
    static_configs:
      - targets: ['worker:50051', 'worker-2:50051']
    metrics_path: '/metrics'
